export const PROFILE_LOAD = 'PROFILE_LOAD';
export const PROFILE_LOAD_SUCCESS = 'PROFILE_LOAD_SUCCESS';
export const PROFILE_LOAD_FAIL = 'PROFILE_LOAD_FAIL';

export const PROFILE_THISWEEK_LOAD = 'PROFILE_THISWEEK_LOAD';
export const PROFILE_THISWEEK_LOAD_SUCCESS = 'PROFILE_THISWEEK_LOAD_SUCCESS';
export const PROFILE_THISWEEK_LOAD_FAIL = 'PROFILE_THISWEEK_LOAD_FAIL';

export const PROFILE_THISMONTH_LOAD = 'PROFILE_THISMONTH_LOAD';
export const PROFILE_THISMONTH_LOAD_SUCCESS = 'PROFILE_THISMONTH_LOAD_SUCCESS';
export const PROFILE_THISMONTH_LOAD_FAIL = 'PROFILE_THISMONTH_LOAD_FAIL';

export const PROFILE_THISOTHER_LOAD = 'PROFILE_THISOTHER_LOAD';
export const PROFILE_THISOTHER_LOAD_SUCCESS = 'PROFILE_THISOTHER_LOAD_SUCCESS';
export const PROFILE_THISOTHER_LOAD_FAIL = 'PROFILE_THISOTHER_LOAD_FAIL';

export const UPDATE_LOGIN_INFO = 'UPDATE_LOGIN_INFO';

export const PROFILE_DETAILS_LOAD = 'PROFILE_DETAILS_LOAD';
export const PROFILE_DETAILS_LOAD_SUCCESS = 'PROFILE_DETAILS_LOAD_SUCCESS';
export const PROFILE_DETAILS_LOAD_FAIL = 'PROFILE_DETAILS_LOAD_FAIL';

export const PROFILE_DETAILS_UPDATE = 'PROFILE_DETAILS_UPDATE';
export const PROFILE_DETAILS_UPDATE_SUCCESS = 'PROFILE_DETAILS_UPDATE_SUCCESS';
export const PROFILE_DETAILS_UPDATE_FAIL = 'PROFILE_DETAILS_UPDATE_FAIL';

export const PROFILE_DETAILS_CREATE = 'PROFILE_DETAILS_CREATE';
export const PROFILE_DETAILS_CREATE_SUCCESS = 'PROFILE_DETAILS_CREATE_SUCCESS';
export const PROFILE_DETAILS_CREATE_FAIL = 'PROFILE_DETAILS_CREATE_FAIL';

export const PATCH_PROFILE_FAILED = 'PATCH_PROFILE_FAILED';

export const VIEW_DETAIL_DATA_ID = 'VIEW_DETAIL_DATA_ID';

export const RESET_PROFILE_DETAILS_DATA = 'RESET_PROFILE_DETAILS_DATA';

export const CLOSE_MODAL_SUCCESS = 'CLOSE_MODAL_SUCCESS';

export const BOOK_MEETING_ROOM = 'BOOK_MEETING_ROOM';
export const BOOK_MEETING_ROOM_SUCCESS = 'BOOK_MEETING_ROOM_SUCCESS';
export const BOOK_MEETING_ROOM_FAILED = 'BOOK_MEETING_ROOM_FAILED';
