export const PROFILE_LOAD = 'PROFILE_LOAD';
export const PROFILE_LOAD_SUCCESS = 'PROFILE_LOAD_SUCCESS';

export const PROFILE_LOAD_THISWEEK = 'PROFILE_LOAD_THISWEEK';
export const PROFILE_LOAD_SUCCESS_THISWEEK = 'PROFILE_LOAD_SUCCESS_THISWEEK';

export const PROFILE_LOAD_THISMONTH = 'PROFILE_LOAD_THISMONTH';
export const PROFILE_LOAD_SUCCESS_THISMONTH = 'PROFILE_LOAD_SUCCESS_THISMONTH';


export const LOGIN_CHECK = 'LOGIN_CHECK';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const PROFILEDETAILS_LOAD = 'PROFILEDETAILS_LOAD';
export const PROFILEDETAILS_LOAD_SUCCESS = 'PROFILEDETAILS_LOAD_SUCCESS';
export const PROFILEDETAILS_PATCH = 'PROFILEDETAILS_PATCH';

export const VIEW_DETAIL_DATA_ID = 'VIEW_DETAIL_DATA_ID';

export const ADD_PROFILE = 'ADD_PROFILE';
